### ISSUE TITLE
Maybe there is a typo in readme

### ISSUE THREAD

**Issue by skyf0cker** [Soptq/hack-boba-bundlr-arweave#1]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/32331521/163309859-8e46f4e6-f454-4f55-9a5a-d83bc7c3d1f3.png">

maybe clone the repo instead fork it?

**Comment by Soptq** [comment]
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/32331521/163309859-8e46f4e6-f454-4f55-9a5a-d83bc7c3d1f3.png">
> 
> maybe clone the repo instead fork it?

Yes, thanks for you correction, will fix it asap :)
